spring:
  profiles:
    include: local
  application:
    name: karrotcruit-homework
  datasource:
    url: jdbc:h2:~/karrotcruit;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc.batch_size: ${batchSize}
    hibernate:
      ddl-auto: create-drop

batchSize: 50

#logging:
#  level:
#    org.springframework.jdbc.core: debug
#    org.hibernate.SQL: debug